apiVersion: v1
kind: Pod
metadata:
  name: react-app-pod
  labels:
    app: react-app
spec:
  containers:
    - name: react-app-container
      image: vishwasanthosh/reactapp
      ports:
        - containerPort: 3080
  serviceAccountName: default   

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3080
  type: NodePort
