name: Deploy to Kubernetes

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner to use

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Action to checkout your repository

    - name: minikube start
      run: minikube start
      
    - name: minikube metrics-server
      run: minikube addons enable metrics-server

    - name: namespace 
      run: kubectl get ns
    - name: Create Service 
      run: |
        kubectl get serviceaccounts  
        kubectl create serviceaccount default
        kubectl config set-context --current --namespace=default
        kubectl taint nodes  mildevkub020 node-role.kubernetes.io/master-
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f pod-definition.yaml

    - name: Get pods
      run: kubectl get pods
    
    - name: Get pods
      run: |
        kubectl get pods
        kubectl describe pod react-app-pod
        
