name: Deploy to Kubernetes

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner to use

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Action to checkout your repository

    - name: Setup Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      run: minikube start
      
    - name: Enable Minikube addons
      run: minikube addons enable metrics-server

    - name: Get namespaces 
      run: kubectl get ns

    - name: Create Service Account 
      run: |
        kubectl create serviceaccount default
        kubectl config set-context --current --namespace=default
        
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f pod-definition.yaml

    - name: Get pods
      run: kubectl get pods
    
    - name: Describe pod
      run: kubectl describe pod react-app-pod -n default
