name: Deploy to Kubernetes

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest  # The runner to use

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Action to checkout your repository

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1  # Action to set up kubectl
    - name: minikube start
      run: minikube start
      
    - name: minikube metrics-server
      run: minikube addons enable metrics-server

    - name: Get pods
      run: kubectl get pods

    - name: Get Service
      run: kubectl get svc
      
    - name: Create Service
      run: |
        kubectl get serviceaccounts  
        kubectl create serviceaccount default
        kubectl config set-context --current --namespace=default
      
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f pod-definition.yaml

    - name: Get pods
      run: kubectl get pods
    - name: Get Service
      run: kubectl get svc
        
        
